# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mobgpsd}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-06-11}
  s.default_executable = %q{mobgpsd}
  s.description = %q{Turns your smartphone in a gpsd device (think wardriving)}
  s.email = %q{x@nofxx.com}
  s.executables = ["mobgpsd"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/mobgpsd",
     "lib/mobgpsd.rb",
     "lib/mobgpsd/gpsd.rb",
     "lib/mobgpsd/nmea.rb",
     "lib/mobgpsd/web.rb",
     "mobgpsd.gemspec",
     "spec/mobgpsd/core_spec.rb",
     "spec/mobgpsd/nmea_spec.rb",
     "spec/mobgpsd_spec.rb",
     "spec/serial.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/mobgpsd}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Use your mobile as GPS device on the pc}
  s.test_files = [
    "spec/serial.rb",
     "spec/spec_helper.rb",
     "spec/mobgpsd/core_spec.rb",
     "spec/mobgpsd/nmea_spec.rb",
     "spec/mobgpsd_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

